# Generated by Django 3.1 on 2020-08-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200819_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='members',
            name='nickname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
