# Generated by Django 3.1 on 2020-09-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200831_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='auth',
            field=models.CharField(max_length=10, null=True, verbose_name='인증번호'),
        ),
    ]
