# Generated by Django 3.1 on 2020-09-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_members_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='auth',
        ),
    ]
