# Generated by Django 3.1 on 2020-08-19 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('symptom', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('receipt', models.FileField(blank=True, upload_to='photo_%Y_%m_%d')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=20)),
                ('writedate', models.DateTimeField(auto_now_add=True)),
                ('recommend', models.IntegerField(default=0)),
                ('rate', models.IntegerField()),
                ('visitdate', models.DateTimeField()),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('symp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('commentdate', models.DateTimeField(auto_now=True)),
                ('commenttext', models.TextField()),
                ('contentsnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.contents')),
            ],
        ),
    ]
