# Generated by Django 3.1 on 2020-08-31 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200831_1714'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='nickname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.members'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='receipt',
            field=models.FileField(blank=True, upload_to='media/photo_%Y_%m_%d'),
        ),
    ]
