# Generated by Django 3.1 on 2020-08-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200831_1714'),
        ('reviews', '0002_auto_20200831_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members'),
        ),
    ]
